### ISSUE TITLE
Rework subscribe function to add more typesafety

### ISSUE THREAD

**Issue by kalvinpearce** [kalvinpearce/seorsum#1]
Need to look into if theres a better way of subscribing to state pieces. At the moment there is little safety around what gets put in the stateValue param. Would be good to rework to make it more typesafe if possible?

This would remove the need for branching statement and broken subscribes.

https://github.com/kalvinpearce/seorsum/blob/446d28fc51b73fddca562fd24cd6b17f9ea3244c/src/index.ts#L44-L60

**Comment by kalvinpearce** [comment]
Something like this could be in the right direction?
https://github.com/RafaelSalguero/DeepPath
```ts
```

**Comment by kalvinpearce** [comment]
Something like this could be on the right track?
https://github.com/RafaelSalguero/DeepPath/

The idea is that you can curry the path out from an object type using keyof typed options.
Perhaps subscribe could be more along the lines of `subscibe('name')('first');`?

**Comment by kalvinpearce** [comment]
So this is now an important fix. The subscribing is based on the way you write the state piece out and if it compiles differently then it can break.
Since it is based on this regex it is quite easy to break and it breaks silently.
https://github.com/kalvinpearce/seorsum/blob/a90cefd848b48a17e8544e2e70983aad8d1f5e65/src/index.ts#L49

**Comment by kalvinpearce** [comment]
This looks like a promising solution rather than currying.
https://github.com/microsoft/TypeScript/issues/12290#issuecomment-449425101/
With some adapting it means you could run `subscribe(['name', 'first'1]);` and each element in the array would be a string literal for the possible keys of state for that path. Limitation is that it only supports up to 7 layers deep but could be a good solution for now.

**Comment by kalvinpearce** [comment]
This is somewhat solved in #2 but I still feel like this needs to be left open and continue to investigate the solution. As @JamesYFC has suggested, maybe the solution could be to add more layers to the tuple path type but it seems limiting to have a hard upper limit of how deep the state can be until intellesense breaks.

**Comment by kalvinpearce** [comment]
@JamesYFC there is an issue with the new tuple path method that we missed. It seems to only support a depth of 2 at the moment
```ts
subscribe(['one', 'two']); // Works fine
subscribe(['one', 'two', 'three']); //Types of property '['2']' are incompatible.
      // Type 'string' is not assignable to type 'undefined'.
```

**Comment by JamesYFC** [comment]
Will take a look in a day or two, internet access is sketchy atm


Sent from Yahoo Mail for iPhone


On Tuesday, November 19, 2019, 1:19 pm, Kalvin Pearce <notifications@github.com> wrote:


@JamesYFC there is an issue with the new tuple path method that we missed. It seems to only support a depth of 2 at the moment
subscribe(['one', 'two']); // Works fine
subscribe(['one', 'two', 'three']); //Types of property '['2']' are incompatible.
      // Type 'string' is not assignable to type 'undefined'.

**Comment by kalvinpearce** [comment]
Closing now due to being fixed in https://github.com/kalvinpearce/seorsum/commit/b19bf2f4614b002e70a3958dc82e07e082230655

**Comment by kalvinpearce** [comment]
Current limit is 10 paths deep but after adding more I realised TS currently doesn't types of more than 10 deep... at 13 it will throw errors.
